# Generated by Django 2.2.11 on 2020-04-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.Student')),
            ],
        ),
    ]
