# Generated by Django 2.2.11 on 2020-04-28 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='students_app.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
