# Generated by Django 2.2.11 on 2020-04-28 16:00

from django.db import migrations
# from students_app.models import Student WRONG


def info(student):
    return f'{student.id} {student.first_name} {student.last_name} {student.age} {student.phone}'


def forwards(apps, schema_editor):
    Student = apps.get_model('students_app', 'Student')
    for student in Student.objects.exclude(phone='').iterator():
        phone = ''.join(char for char in student.phone if char.isdigit())
        print(info(student))
        # print(student.info())  WRONG
        student.phone = phone
        student.save()


def backwards(apps, schema_editor):
    print('backwards ' * 10)


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_auto_20200428_1559'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
